# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- name: Run make ensure inside the application
  command:
    cmd: /home/isucon/go/bin/dep ensure -vendor-only
    chdir: /home/isucon/isucon-all/webapp/go/src/app
  environment:
    GOPATH: /home/isucon/isucon-all/webapp/go/
  become: yes
  become_user: isucon
  tags:
    - application

- name: Build the application
  command:
    cmd: /home/isucon/local/go/bin/go build -v app
    chdir: /home/isucon/isucon-all/webapp/go/
  environment:
    GOPATH: /home/isucon/isucon-all/webapp/go/
  become: yes
  become_user: isucon
  tags:
    - application
