# -*- mode: Yaml; -*-
# vi: set ts=2 sw=2 sts=0 et:

---
- name: Install Package
  apt:
    state: present
    name:
      - nginx

# http://docs.ansible.com/ansible/latest/file_module.html
- name: Disable default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx config
  copy:
    src: etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-available/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - nginx.conf
  tags:
    - nginx

- name: Enable the config
  file:
    path: /etc/nginx/sites-enabled/nginx.conf
    src: /etc/nginx/sites-available/nginx.conf
    state: link
  notify:
    - reload nginx
